In [ ]:
#Array Operation

In [59]:
import numpy as np

In [60]:
a1 = np.arange(10,20)
aa = np.reshape(a1,[1,10])
aa

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [61]:
a2 = np.arange(100,110)
bb = np.reshape(a2,[1,10])
bb


array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [62]:
np.row((aa,bb))


/var/folders/c3/92f17n4j6pq0qd807jhctp480000gn/T/ipykernel_13423/1147417238.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((aa,bb))


array([[ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [ ]:
#Broadcasting -- sare mai hoga jo hoga 

In [ ]:
# arr + 10

In [ ]:
#Deep ane Shalow Copy

In [14]:
arr = np.arange(1, 21)

In [15]:
slice = arr[:5]
slice = slice + 10
print(slice)

[11 12 13 14 15]


In [ ]:
#Matrix Operation
# A @ B matrics mul
# np.dot(A,B)
# Arr.T to transpose

In [ ]:
#Adv array maniplation

In [ ]:
#Stacking Array

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [ ]:
#Splitting Array