In [2]:
import numpy as np

In [3]:
arr = np.arange(1,31).reshape(6,5)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [4]:
slice = arr[3: , 3: ]

In [5]:
print(slice)

[[19 20]
 [24 25]
 [29 30]]


In [7]:
arr = np.arange(12,21)
bool_i = arr%2 == 0 
print(bool_i)

[ True False  True False  True False  True False  True]


In [8]:
arr = arr[bool_i]
print(arr)

[12 14 16 18 20]
